version: '3.7'

services:
  spark-master:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      - SPARK_CONF_OPTS=--conf "spark.log.level=ERROR"
    volumes:
      - ./transform:/transform/
      - ./log4j.properties:/opt/bitnami/spark/conf/log4j.propertiess

  spark-worker-1:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_CONF_OPTS=--conf "spark.log.level=ERROR"
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./transform:/transform/
      - ./log4j.properties:/opt/bitnami/spark/conf/log4j.propertiess

  spark-worker-2:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_CONF_OPTS=--conf "spark.log.level=ERROR"
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./transform:/transform/
      - ./log4j.properties:/opt/bitnami/spark/conf/log4j.propertiess